### ISSUE TITLE
disabling second layer for dispensing

### ISSUE THREAD

**Issue by ojanovsky** [hzeller/rpt2pnp#4]
Hello, 
I am trying to use this for paste dispensing. My design has parts on both side, but I need to paste only one layer. How to do it?

Regards
  Oja

**Comment by hzeller** [comment]
Ok, fixed.
I think I never used it with a board that had pads to be dispensed on the bottom side.
Now, the default is the top side, the bottom side you choose with `-b`.

**Comment by ojanovsky** [comment]
Hello,
you are very fast. Thank you. 
I am thinking about second feature. I want to specify references - parts which will not be placed - for example: RELAYS, REZISTORS ... because I have a few variants on one board.

Regards
    Oja

**Comment by hzeller** [comment]
Alright, added a `-x` option provide a list of component designators to exclude from dispensing.
```
./rpt2pnp -xC1,D13,R2 -d my.rpt
```

**Comment by ojanovsky** [comment]
Thank you very much. You are code devil :+1:
